package rand

import (
	"crypto/rand"
	"encoding/base64"
)

// RememberTokenBytes in the integer number
// of bytes to be use for generating
// the remember token
const RememberTokenBytes = 32

// Bytes creates a bytes slice of length int
func Bytes(n int) ([]byte, error) {
	b := make([]byte, n)
	_, err := rand.Read(b)
	if err != nil {
		return nil, err
	}
	return b, nil
}

// String returns a safe to use base64 url encoded string
func String(nBytes int) (string, error) {
	b, err := Bytes(nBytes)
	if err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(b), nil
}

// RememberToken casts the token bytes to a string
func RememberToken() (string, error) {
	return String(RememberTokenBytes)
}

// NBytes returns the number of bytes used in any string
// generated by the String or RememberToken functions in
// this package.
func NBytes(base64String string) (int, error) {
	b, err := base64.URLEncoding.DecodeString(base64String)
	if err != nil {
		return -1, err
	}
	return len(b), nil
}
